Stash/Stash/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using Services;

namespace Stash.Controllers
{
    public class GroupController : Controller
    {
        private GroupServices Service = new GroupServices();

        public ActionResult Index()
        {
            return View(Service.GroupIndex());
        }

        public ActionResult CreateGroup() {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult CreateGroup(Itemgroup Group) {
            throw new NotImplementedException();
        }

        public ActionResult DeleteGroup() {
            throw new NotImplementedException();
        }

        public ActionResult AddItemToGroup() {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Updates both models in the database
        /// </summary>
        /// <param name="Group"></param>
        /// <param name="Item"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddItemToGroup(Itemgroup Group, Item Item)
        {
            throw new NotImplementedException();
        }
    }
}

Stash/Stash/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlTypes;
using Entities;
using Services;
using System.Net;

namespace Stash.Controllers
{
    public class ItemController : Controller
    {
        //private DataAccess.DataAccess dataAccess = new DataAccess.DataAccess();
        //private StashEntities db = new StashEntities();
        private ItemServices Service = new ItemServices();

        /// <summary>
        /// View of all items. 
        /// Create/edit/delete from this page.
        /// </summary>
        /// <author>Daniel Sacdalan</author>
        /// <returns></returns>
        public ActionResult Index(string searchString)
        {
            return View(Service.GetDetails(searchString));
        }

        /// <summary>
        /// Create Item Page
        /// </summary>
        /// <author>Matt Lucrida and Daniel Sacdalan</author>
        /// <returns></returns>
        public ActionResult CreateItem()
        {
            var newItem = Service.InitializeItem();
            return View(newItem);
        }

        /// <summary>
        /// Saves item add to db.
        /// </summary>
        /// <author>Matt Lucrida and Daniel Sacdalan</author>
        /// <param name="newItem"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateItem([Bind(Include = "RFIDkey,name,object_description,itemgroupkey,photokey,create_date,delete_date")]Item newItem)
        {
            if(ModelState.IsValid)
            {
                // service path seems redundant :/
                Service.AddNewItem(newItem);
                return RedirectToAction("Index");
            }
            return RedirectToAction("CreateItem");
        }

        /// <summary>
        /// This also includes adding photos
        /// </summary>
        /// <returns></returns>
        public ActionResult UpdateItem(int id)
        {
            //if (id == null) {
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            Item Item = Service.GetItem(id);
            return View(Item);
        }

        [HttpPost]
        public ActionResult UpdateItem([Bind(Include = "itemkey,RFIDkey,name,object_description,itemgroupkey,photokey,create_date,delete_date")]Item Item)
        {
            if (ModelState.IsValid)
            {
                Service.UpdateItem(Item);
                return RedirectToAction("Index");
            }
            return View(Item);
        }

        public ActionResult DeleteItem(int id) {
            Item Item = Service.GetItem(id);
            return View(Item);
        }

        [HttpPost]
        public ActionResult DeleteItem([Bind(Include = "itemkey,RFIDkey,name,object_description,itemgroupkey,photokey,create_date,delete_date")]Item Item)
        {
            if (ModelState.IsValid)
            {
                Service.DeleteItem(Item);
                return RedirectToAction("Index");
            }
            return View(Item);
        }

    }
}

Stash/Stash/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stash</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">
                    <img alt="Stash" src="~/Content/stashtag.png" height="30" width="30"/>
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Stash", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Boxes", "Index", "Home")</li>
                    <li>@Html.ActionLink("Items", "Index", "Item")</li>
                    @*<li>@Html.ActionLink("Groups", "Index", "Group")</li>*@
                    <li>@Html.ActionLink("About", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <br />
    <div class="container body-content">
     @RenderBody()
    </div>
    <div>
    <hr />
    <footer>
        <p align="center">&copy; @DateTime.Now.Year - Team 1700</p>
    </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

</body>
</html>